config/routes.rb
Rails.application.routes.draw do

  resources :events do
    resources :attendees, :controller => 'event_attendees'
  end

  root 'events#index'

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  belongs_to :event
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :events
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates_presence_of :name
  has_many :attendees
  belongs_to :category
  has_one :location
  has_many :event_groupships
  has_many :groups, :through => :event_groupships

  #delegate :name, :to => :category, :prefix => true, :allow_nil => true
end

app/models/event_groupship.rb
class EventGroupship < ActiveRecord::Base
  belongs_to :event
  belongs_to :group
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :event_groupships
  has_many :events, :through => :event_groupships
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  before_action :find_event

  def index
    @attendees = @event.attendees
  end

  def show
    @attendee = @event.attendees.find(params[:id])
  end

  def new
    @attendee = @event.attendees.build
  end

  def create
    @attendee = @event.attendees.build(attendee_params)
    if @attendee.save
      redirect_to event_attendees_url(@event)
    else
      render :action => :new
    end
  end

  def edit
    @attendee = @event.attendees.find(params[:id])
  end

  def update
    @attendee = @event.attendees.find(params[:id])
    if @attendee.update(attendee_params)
      redirect_to event_attendees_url(@event)
    else
      render :action => :edit
    end
  end

  def destroy
    @attendee = @event.attendees.find(params[:id])
    @attendee.destroy
    redirect_to event_attendees_url(@event)
  end

protected
  def find_event
    @event = Event.find(params[:event_id])
  end

  def attendee_params
    params.require(:attendee).permit(:name)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :get_event, :only => [:show, :edit, :update, :destroy]
  
  def index
    #@events = Event.all
    @events = Event.page(params[:page]).per(10)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = "新增成功"
      redirect_to events_path
    else
      render :action => :new
    end
  end

  def show
    @page_title = @event.name
  end

  def edit
  end

  def update
    if @event.update(event_params)
      flash[:notice] = "更新成功"
      #redirect_to :action => :show, :id => @event.id
      redirect_to event_path(@event)
    else
      render :action => :edit
    end
  end

  def destroy
    @event.destroy
    flash[:alert] = "刪除成功"
    #redirect_to :action => :index
    redirect_to events_path
  end


private
  def get_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :description, :birthday, :location, :category_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/event_attendees/edit.html.erb
<%= form_for @attendee, :url => event_attendee_path(@event, @attendee), :html => {:method => :patch} do |f| %>
  <%= f.text_field :name %>
  </br>
  <%= f.submit %>
<% end %>

app/views/event_attendees/index.html.erb
<ul>
  <% @attendees.each do |attendee| %>
  <li>
    <%= attendee.name %>
    <%= link_to 'Show', event_attendee_path(@event, attendee) %>
    <%= link_to 'Edit', edit_event_attendee_path(@event, attendee) %>
    <%= link_to 'Destroy', event_attendee_path(@event, attendee), :method => :delete %>

  </li>
  <% end %>
</ul>

<%= link_to 'New attendee', new_event_attendee_path(@event) %>

</br>
</br>

<%= link_to 'Back to index', events_path %>

app/views/event_attendees/new.html.erb
<%= form_for @attendee, :url => event_attendees_path(@event) do |f| %>
  <%= f.text_field :name %>
  </br>
  <%= f.submit %>
<% end %>

</br>
</br>

<%= link_to 'Back to index', events_path %>

app/views/event_attendees/show.html.erb
<p>Name: <%= @attendee.name %></p>

</br>
</br>

<%= link_to 'Back to attendees list', event_attendees_path(@event) %>

app/views/events/_form.html.erb
<% if @event.errors.any? %>

  <ul>
    <li>
      <% @event.errors.full_messages.each do |msg| %>
      <%= msg %>
      <% end %>
    </li>
  </ul>
<% end %>


</br>
<%= f.label :name, "Name: " %>
<%= f.text_field :name %>
</br>
<%= f.label :description, "Description: " %>
<%= f.text_area :description %>
</br>
<%= f.label :birthday, "Host Day: " %>
<%= f.date_field :birthday %>
</br>
<%= f.collection_select(:category_id, Category.all, :id, :name) %>
</br>

app/views/events/edit.html.erb
<%= form_for @event, :url => event_path(@event), :method => :patch do |f| %>

  <%= render :partial => "form", :locals => {:f => f}  %>

  <%= f.submit "Update" %>

<% end %>

<%= link_to "Back to index", events_path %>

app/views/events/index.html.erb
<h2>Event list</h2>

<% @events.each do |e| %>

<ul>
    <li>
      <%= e.name %>
      <%= link_to "Show", event_path(e) %>
      <%= link_to "Edit", edit_event_path(e) %>
      <%= link_to "Destroy", event_path(e), :method => :delete %>
      <%= link_to "Attendees", event_attendees_path(e) %>
    </li>

</ul>

<% end %>

<p>
<%= link_to "New Event", new_event_path %>
</p>
<%= paginate @events %>

app/views/events/new.html.erb
<%= form_for @event, :url => events_path do |f| %>

  <%= render :partial => "form", :locals => {:f => f} %>
  <%= f.submit "Create" %>

<% end %>

<%= link_to "Back to index", events_path %>

app/views/events/show.html.erb
<h3 style="color: gray">Name:</h3>
<%= @event.name %>
</br>
</br>

<h3 style="color: gray">Description:</h3>
<%= simple_format @event.description %>
</br>

<h3 style="color: gray">Host Day:</h3>
<%= @event.birthday %>
</br>
</br>
<h3 style="color: gray">Category:</h3>
<%= @event.category.try(:name) %>

</br>
</br>
</br>
<%= link_to "Back to index", events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Rails Test" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<p style="color: green"><%= flash[:notice] %></p>
<p style="color: red"><%= flash[:alert] %></p>

</body>
</html>